spring:
  application:
    name: SEE-INSIGHT
  datasource:
    url: jdbc:mysql://localhost:3306/see_insight
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
